## Imports

In [1]:
import pandas as pd
import datetime

import plotly.express as px
import plotly.io as pio

template_plotly = dict(
    layout = dict(
        plot_bgcolor = 'white',
        xaxis = dict(tickfont = dict(size = 10, color = 'gray')),
        yaxis = dict(tickfont = dict(size = 10, color = 'gray'))
    )
)

pio.templates['template_default'] = template_plotly
pio.templates.default = 'template_default'

In [2]:
from os import walk
from typing import List

def listar_arquivos_pasta(folder_path: str) -> List[str]:

    files = []
    for (dirpath, dirnames, filenames) in walk(folder_path):
        files.extend(filenames)

    return files

## Tabela dimensão dos ativos

In [3]:
df_setores = pd.read_excel('refined/ativos_ibov.xlsx')
print(f"Tamanho da tabela: {df_setores.shape[0]}")
df_setores.head(10)

Tamanho da tabela: 85

,ticker,empresa,tipo_acao,complemento_tipo,segm_gov,qtd_teorica,pct_part,setor,subsetor,segmento
0,ALOS3,ALLOS,ON,NaN,NM,466135796,0.548,Financeiro,Exploração de Imóveis,Exploração de Imóveis
1,ABEV3,AMBEV S/A,ON,NaN,NaN,4273841357,2.495,Consumo não Cíclico,Bebidas,Cervejas e Refrigerantes
2,ASAI3,ASSAI,ON,NaN,NM,1338601375,0.420,Consumo não Cíclico,Comércio e Distribuição,Alimentos
3,AURE3,AUREN,ON,NaN,NM,318338365,0.141,Utilidade Pública,Energia Elétrica,Energia Elétrica
4,AXIA3,AXIA ENERGIA,ON,ATZ,N1,1945846761,4.401,Utilidade Pública,Energia Elétrica,Energia Elétrica
5,AXIA6,AXIA ENERGIA,PNB,NaN,N1,270655585,0.667,Utilidade Pública,Energia Elétrica,Energia Elétrica
6,AXIA7,AXIA ENERGIA,PNC,NaN,N1,582580795,1.278,Utilidade Pública,Energia Elétrica,Energia Elétrica
7,AZZA3,AZZAS 2154,ON,NaN,NM,132447688,0.124,Consumo Cíclico,Comércio Varejista,"Tecidos, Vestuário e Calçados"
8,B3SA3,B3,ON,NaN,NM,5196371458,3.434,Financeiro,Serviços Financeiros Diversos,Serviços Financeiros Diversos
9,BBSE3,BBSEGURIDADE,ON,NaN,NM,616186808,0.808,Financeiro,Previdência e Seguros,Seguradoras

In [6]:
df_setores[['setor']].value_counts().reset_index()

                             setor  count
0                  Consumo Cíclico     16
1                       Financeiro     15
2                Utilidade Pública     15
3                Materiais Básicos     10
4  Petróleo, Gás e Biocombustíveis      9
5              Consumo não Cíclico      7
6                 Bens Industriais      5
7                            Saúde      5
8                     Comunicações      2
9         Tecnologia da Informação      1

In [4]:
arquivos = listar_arquivos_pasta('scraped/')
df = pd.DataFrame()

for arquivo in arquivos:
    tmp = pd.read_csv(f"scraped/{arquivo}")
    df = pd.concat([df, tmp])

df = df[['date', 'codigo', 'price']]

In [5]:
print(f"Horário da execução:    {pd.to_datetime(datetime.datetime.now()).round('s')}")
print(f"Quantidade de arquivos: {len(arquivos)}")

Horário da execução:    2026-03-19 21:38:22
Quantidade de arquivos: 126

In [6]:
# lista_stocks = df_setores[df_setores['setor'] == 'Petróleo, Gás e Biocombustíveis']['ticker'].unique()
lista_stocks = df_setores[df_setores['setor'] == 'Financeiro']['ticker'].unique()
# lista_stocks = df_setores[df_setores['setor'] == 'Consumo Cíclico']['ticker'].unique()

for stock in lista_stocks:
    tmp = df[df['codigo'] == stock]
    # display(tmp)
    fig = px.line(tmp, x = 'date', y = 'price', markers = True)
    fig.update_layout(title = stock, height = 300, width = 1200)
    # fig.update_yaxes(range = (0, max(tmp['price'] + 10)))
    fig.show()
    # break